#!/bin/bash

usage() {
    printf "\nUsage: mkrelease [-c] [-d] [-p] [-u]"
    printf "\nWhere:"
    printf "\n\t-c indicates clean first"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-p indicates skip package creation step"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

CLEAN=
DRAFT=
PACKAGE=1
BRANCH="main"
while getopts "b:cdpu" flag; do
    case $flag in
        b)
            BRANCH="${OPTARG}"
            ;;
        c)
            CLEAN=1
            ;;
        d)
            DRAFT="--draft"
            ;;
        p)
            PACKAGE=
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ -f VERSION ]; then
  source VERSION
else
  echo "ERROR: missing VERSION"
  exit 1
fi

ANNO="LifeBots Control Panel release, version ${VERSION}"

if [ -f ${HOME}/.mrprivate ]; then
  source ${HOME}/.mrprivate
fi

make clean
make
[ -f LifeBotsControlPanel.zip ] || {
  echo "ERROR: cannot locate LifeBotsControlPanel.zip"
  exit 1
}

tar cf - Examples/*.lsl | gzip -9 > Examples-${VERSION}.tar.gz
tar cf - LifeBotsControlPanel.lsl \
         Examples-${VERSION}.tar.gz \
         Configuration \
         LICENSE \
         VERSION | gzip -9 > LifeBotsControlPanel-${VERSION}.tar.gz

gh release create v${VERSION} ${DRAFT} \
                  --title "${ANNO}" \
                  --target "${BRANCH}" \
                  --notes-file Release_Notes.md \
                  LifeBotsControlPanel.lsl \
                  Configuration \
                  Examples/header.lsl \
                  LifeBotsControlPanel-${VERSION}.tar.gz \
                  LifeBotsControlPanel.zip

git fetch --tags origin
rm -f Examples-${VERSION}.tar.gz LifeBotsControlPanel-${VERSION}.tar.gz
make clean
